server:
  port: ${port:9004}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: catalog_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 1.0
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  hateoas:
    use-hal-as-default-json-media-type: false
  kafka:
      properties:
        sasl:
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required
              username="USERNAME" password="PASSWORD";
          mechanism: SCRAM-SHA-256
        security:
          protocol: SASL_SSL
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bookstore.ccz3nxew3wxs.ap-southeast-1.rds.amazonaws.com:3306/catalogservicedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: jerrytran97
#    url: jdbc:mysql://localhost:3306/catalogservicedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: Jerrytran97@
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.bookstore.catalogservice.*: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder=TRACE:


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

  security:
    enabled: false


cloud:
  aws:
    credentials:
      access-key: AKIATSR2NBN46TPXIG5W
      secret-key: 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
#      access-key: MJAAJXUVR8UX3K789PMF
#      secret-key: V56i2LOGxYtcWiDWEwSTQlxi8CMh4NhWm8cePRs5
    region:
      static: Asia Pacific (Singapore) ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: phuc-bookstore
