server:
  port: ${SERVER_PORT:9005}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

service:
  stripeKey: sk_test_51HyGx6G9R9y827ntfKTizO243LzKHnaNIucO8i7apU0zuTIE5iNAes6l64aoWczGwiCnnBNsvvrgS95nfpbWa2cw00FnScmrhd

spring:
  application:
    name: payment-service
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: catalog_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 1.0
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentservicedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Jerrytran97@

logging:
  level:
    com.bookstore.paymentservice.*: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

  security:
    enabled: false